version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/openjdk:20.0.1
    steps:
      - checkout
      - run: mvn clean
      - run: mvn test
      - run: mvn install